package com.company.google;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;


public class Main {

    public static void main(String[] args) throws InterruptedException {
            System.setProperty("webdriver.gecko.driver", "C:\\Users\\abdul\\Downloads\\selenium\\geckodriver-v0.24.0-win64\\geckodriver.exe");
            WebDriver driver = new FirefoxDriver();
            //WebDriver driver = new ChromeDriver();
            driver.get("http://www.gmail.com/");
            driver.manage().window().maximize();
            driver.findElement(By.id("identifierId")).sendKeys("testj123s@gmail.com");
            driver.findElement(By.className("CwaK9")).click();
            Thread.sleep(2000);
            driver.findElement(By.name("password")).sendKeys("javatest1234");
            driver.findElement(By.className("CwaK9")).click();

            Thread.sleep(5000);
            driver.findElement(By.className("aic")).click();
            Thread.sleep(5000);

            driver.findElement(By.className("vO")).sendKeys("tselenium753@gmail.com");
            driver.findElement(By.className("aoT")).sendKeys("Test case");


            driver.findElement(By.className("Am")).sendKeys("This is an autogenerated email");


            driver.findElement(By.className("aoO")).click();


            Thread.sleep(5000);

            driver.findElement(By.className("gbii")).click();

            driver.findElement(By.id("gb_71")).click();

            Thread.sleep(2000);
            driver.quit();


        }

    }